config/routes.rb
Rails.application.routes.draw do
  
  devise_scope :user do
    get "/" => "registrations#new"
    get 'users/sign_in', to: redirect('/')
    get 'users/sign_up', to: redirect('/')
    put '/update' => "registrations#update", as: "user_update"
    get 'users/edit' => "registrations#edit", as: "devise_user_edit"
    get 'users/:id' => "users#show", as: "user_show"
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }

  resources :users do 
    resources :outfits
    resources :closets, only: [:create]
  end

  resources :scenarios
  resources :answers
  resources :items
  
  get '/about' => 'welcome#about', as: "about"
  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
      can :read, :all
      can [:update, :destroy], User, :id => user.id
      can [:destroy], Outfit, :styled_id => user.id
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :scenario
  belongs_to :option
  
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
  
  
end

app/models/closet.rb
class Closet < ActiveRecord::Base
  belongs_to :outfit
  belongs_to :item
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :options
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :closets, dependent: :destroy
  has_many :outfits, :through => :closets
end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :event
  has_many :answers
end

app/models/outfit.rb
class Outfit < ActiveRecord::Base
  belongs_to :styled, :class_name => "User", :foreign_key => "styled_id"
  belongs_to :stylist, :class_name => "User", :foreign_key => "stylist_id"
  has_many :closets, dependent: :delete_all
  has_many :items, :through => :closets
end

app/models/scenario.rb
class Scenario < ActiveRecord::Base
  belongs_to :user
  has_many :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
         
  mount_uploader :picture, PictureUploader
  
  has_many :scenarios
  has_many :outfits
  has_many :authentications
  

                
  validates :first_name,  presence: true
  validates :last_name,  presence: true
  validate  :picture_size
  
         
  def apply_omniauth(auth)
    self.email = auth.email
    self.remote_picture_url = auth.info.image if self.picture.blank?
    self.first_name = auth.info.first_name
    self.last_name = auth.info.last_name
    authentications.build(provider: auth.provider, uid: auth.uid, token: auth.extension.token)
  end       

  def self.from_omniauth(auth)
    if self.where(email: auth.info.email).exists?
      existing_user = self.where(email: auth.info.email).first
      existing_user.provider = auth.provider
      existing_user.uid = auth.uid
      existin_user.remote_picture_url = auth.info.image if existing_user.picture.blank?
    else
      existing_user = where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.first_name = auth.info.first_name   # assuming the user model has a name
        user.last_name = auth.info.last_name
        user.remote_picture_url = auth.info.image # assuming the user model has an image
      end
    end
    existing_user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  
  # Returns search query
  def self.search(params)
    where("(UPPER(first_name) LIKE ?) OR (UPPER(last_name) LIKE ?)", "%#{params.upcase}%", "%#{params.upcase}%") 
  end

  # Find user responses for scenarios
  def self.list_answers(user)
    # responses = []
    sub_responses = {}
	  scenario = user.scenarios.order("created_at").last
    if !scenario.nil?
      sub_responses["Event"] = scenario.answers.first.option.event.dress_me_for
		  scenario.answers.map do |answer|
        #sub_responses << options.possible_response if !options.nil?
        #response = options.possible_response if !options.nil?
        if !answer.option_id.nil?
          options = Option.all.find_by(id: answer.option_id)
          case options.question_type
          when "And:"
            sub_responses["And"] = options.possible_response if !options.nil?
          when "Also:"
            sub_responses["Also"]= options.possible_response if !options.nil?
          when "With:"
            sub_responses["With"] = options.possible_response if !options.nil?
          end
        end
        if answer.type_in.present?
            sub_responses["Other"] = answer.type_in
        end
        if answer.date.present?
            sub_responses["Date"] = answer.date
        end
      end
    end
      #responses << sub_responses
		
    #responses
    sub_responses.default = "-----"
    #responses = []
    #responses << sub_responses
    return sub_responses
  end 


  
  private
  
  # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:index]
  
  def index
    @items = Item.all.paginate(:page => params[:page])
  end
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  def new
    #@outfit = current_user.outfits.new
    #@outfit_id = @outfit.id
    @items = Item.all.paginate(:page => params[:page], per_page: 24)
  end  
  
  def show
  	@user = User.find(params[:user_id])
  	@outfit = Outfit.where(styled_id: @user.id, id: params[:id]).first
  	@items = @outfit.nil? ? [] : @outfit.items
  end

  def create
  end

  def destroy
  	user = User.find(params[:user_id])
  	outfit = Outfit.where(styled_id: user.id, id: params[:id]).first
  	authorize! :destroy, outfit
  	outfit.destroy
  	redirect_to user_path(user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :json, :html
  
  def index
    if params[:query]
      @users = User.search(params[:query])
    else
      @users = User.all.paginate(:page => params[:page], :per_page => 30)
    end
  end

  def show
    @user = User.find(params[:id])
    @scenario = User.list_answers(@user)
    @answer = Answer.new
    @options = Option.all
    @outfits = Outfit.where(styled_id: @user.id)
    @disabled = @user == current_user ? false : true
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end
  
  def resource
    @resource ||= User.new
  end
  
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  

end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/closets_helper.rb
module ClosetsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/outfits_helper.rb
module OutfitsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/outfits/_outfits.html.erb
	
		<div class="well" style="height: 100%;, width: 100%;">
		<% @items.in_groups_of(6, false).each do |group| %>
		<div class="row" style="padding-left: 10px; padding-right:10px;">
		<% group.each do |item| %>
		<div class="col-md-2" style="padding: 0px;">
		<div class="draggable" data-item-id='<%= item.id %>'>
				<%= image_tag item.picture, class: "imageUpload" %>	
    	<div class="ui-resizable-handle ui-resizable-nw" id="nwgrip"></div>
    	<div class="ui-resizable-handle ui-resizable-ne" id="negrip"></div>
    	<div class="ui-resizable-handle ui-resizable-sw" id="swgrip"></div>
    	<div class="ui-resizable-handle ui-resizable-se" id="segrip"></div>
    	<div class="ui-resizable-handle ui-resizable-n" id="ngrip"></div>
    	<div class="ui-resizable-handle ui-resizable-s" id="sgrip"></div>
    	<div class="ui-resizable-handle ui-resizable-e" id="egrip"></div>
    	<div class="ui-resizable-handle ui-resizable-w" id="wgrip"></div>
			<div class="item_info text-center">
				<%= link_to item.name, item.link %>
				<p>
					<%= item.price %>
				</p>
			</div>
		</div>
			
		</div>
		<% end %>
		</div>
	<% end %>
</div>

app/views/outfits/new.html.erb
<% provide(:title, "Doll Me Up") %>

<div class="container-fluid">
<div class="jumbotron" id='main-jumbotron' style="padding-bottom: 0px; padding-top: 0px;">
	<%= render "layouts/main_navbar" %>
</div>
</div>
<div class="container-fluid" style="padding-top: 0px;">

<div class="row">
	<div class="col-md-6">
	<div id="outfit_canvas" class="big-canvas" style="width: 100%;">
	<div class="well" style="height: 100%;, width: 100%; border-color: #cabe97;">
	</div>
	</div>
	<br>
	<%= button_to "Create", user_closets_path(params[:user_id]), remote: true, class: "paperdolled-button center-block", id: "outfits_button", style: "width: 90%;border-radius:3px;" %>
</div>


	<div class="col-md-6">
	<div id="outfits_well" class="big-canvas" style="width: 100%;">
	
		<%= render 'outfits' %>

	</div>

		<%= will_paginate @items, id: "page_links", style: "margin-top: 0px;", class: "center-block text-center" %>


		
		<%= javascript_tag "var userId = #{params[:user_id]};" %>	
		
		<div id="dialog" title="Basic dialog">
		</div>
	</div>
</div>

app/views/outfits/new.js.erb
$("#outfits_well").html("<%= escape_javascript(render("outfits")) %>");
$('#page_links').html('<%= escape_javascript(will_paginate @items) %>');

app/views/outfits/show.html.erb
<% provide(:title, "Outfit") %>

<div class="container-fluid">
	<div class="jumbotron" id='main-jumbotron' style="padding-bottom: 0px; padding-top: 0px;">
		<%= render "layouts/main_navbar" %>
	</div>
</div>

<div class="container-fluid" style="height: 100%; padding-top: 0px;">
	<div class="row" style="height: 100%; padding-top: 0px;">
		<div class="col-md-12" style="height: 100%;">
			<div class="panel panel-default center-block" style="height: 90vh; width: 107vh; max-width: 100%; border-width: 2px;">
				<div class="panel-body outfit-display-panel" style="height: 100%; width: 100%;">
					<% @items.map do |item| %>
						<div class="small_draggable2" data-item-id='<%= item.id %>' data-top='<%= item.closets.find_by(outfit_id: @outfit.id).y_coordinate %>' data-left='<%= item.closets.find_by(outfit_id: @outfit.id).x_coordinate %>' data-height='<%= item.closets.find_by(outfit_id: @outfit.id).height %>' data-width='<%= item.closets.find_by(outfit_id: @outfit.id).width %>'>
							<%= image_tag item.picture, class: "imageUpload" %>	
						</div>
					<% end %>
				</div>
			</div>
			<% if can? :destroy, @outfit %>
				<%= button_to 'Delete', user_outfit_path(@user, @outfit), method: :delete, data: { confirm: "Are you sure you would like to delete this outfit?" }, title: "Delete", class: "center-block paperdolled-button", style: 'width:107vh; max-width:100%;border-radius: 3px;' %>
			<% end %>
		</div>
	</div>
</div>