config/routes.rb
Rails.application.routes.draw do
  
  devise_scope :user do
    get "/" => "registrations#new"
    get 'users/sign_in', to: redirect('/')
    get 'users/sign_up', to: redirect('/')
    put '/update' => "registrations#update", as: "user_update"
    get 'users/edit' => "registrations#edit", as: "devise_user_edit"
    get 'users/:id' => "users#show", as: "user_show"
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }

  resources :users do 
    resources :outfits
    resources :closets, only: [:create]
  end

  resources :scenarios
  resources :answers
  resources :items
  
  get '/about' => 'welcome#about', as: "about"
  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
         
  mount_uploader :picture, PictureUploader
  
  has_many :scenarios
  has_many :outfits
  has_many :authentications
  

                
  validates :first_name,  presence: true
  validates :last_name,  presence: true
  validate  :picture_size
  
         
  def apply_omniauth(auth)
    self.email = auth.email
    self.remote_picture_url = auth.info.image if self.picture.blank?
    self.first_name = auth.info.first_name
    self.last_name = auth.info.last_name
    authentications.build(provider: auth.provider, uid: auth.uid, token: auth.extension.token)
  end       

  def self.from_omniauth(auth)
    if self.where(email: auth.info.email).exists?
      existing_user = self.where(email: auth.info.email).first
      existing_user.provider = auth.provider
      existing_user.uid = auth.uid
      existin_user.remote_picture_url = auth.info.image if existing_user.picture.blank?
    else
      existing_user = where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.first_name = auth.info.first_name   # assuming the user model has a name
        user.last_name = auth.info.last_name
        user.remote_picture_url = auth.info.image # assuming the user model has an image
      end
    end
    existing_user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  
  # Returns search query
  def self.search(params)
    where("(UPPER(first_name) LIKE ?) OR (UPPER(last_name) LIKE ?)", "%#{params.upcase}%", "%#{params.upcase}%") 
  end

  # Find user responses for scenarios
  def self.list_answers(user)
    # responses = []
    sub_responses = {}
	  scenario = user.scenarios.order("created_at").last
    if !scenario.nil?
      sub_responses["Event"] = scenario.answers.first.option.event.dress_me_for
		  scenario.answers.map do |answer|
        #sub_responses << options.possible_response if !options.nil?
        #response = options.possible_response if !options.nil?
        if !answer.option_id.nil?
          options = Option.all.find_by(id: answer.option_id)
          case options.question_type
          when "And:"
            sub_responses["And"] = options.possible_response if !options.nil?
          when "Also:"
            sub_responses["Also"]= options.possible_response if !options.nil?
          when "With:"
            sub_responses["With"] = options.possible_response if !options.nil?
          end
        end
        if answer.type_in.present?
            sub_responses["Other"] = answer.type_in
        end
        if answer.date.present?
            sub_responses["Date"] = answer.date
        end
      end
    end
      #responses << sub_responses
		
    #responses
    sub_responses.default = "-----"
    #responses = []
    #responses << sub_responses
    return sub_responses
  end 


  
  private
  
  # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :json, :html
  
  def index
    if params[:query]
      @users = User.search(params[:query])
    else
      @users = User.all.paginate(:page => params[:page], :per_page => 30)
    end
  end

  def show
    @user = User.find(params[:id])
    @scenario = User.list_answers(@user)
    @answer = Answer.new
    @options = Option.all
    @outfits = Outfit.where(styled_id: @user.id)
    @disabled = @user == current_user ? false : true
  end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/users/_answers.html.erb
    <!-- Generated by jQuery -->
		<%= form_for [@answer] do |f| %>
  
  		<div class="form-group">
      		<label>Dress me for:</label>
			<%= select_tag :event_id, options_for_select(Event.all.map{ |option| [option.dress_me_for, option.id, { 'data-event-id' => "" }] }), {prompt: "Please select", class: 'form-control'} %>
		</div>
		<fieldset id="event-fieldset" disabled>
		<div class="form-group">
			<label>And:</label>
			<%= select_tag :option_id2, options_for_select(Option.all.where(question_type: "And:").map{ |option| [option.possible_response, option.id, { 'data-event-id' => option.event_id }] }), {prompt: "Please select", class: 'form-control'} %>
		</div>
		<div class="form-group">
			<label>Also:</label>
			<%= select_tag :option_id3, options_for_select(Option.all.where(question_type: "Also:").map{ |option| [option.possible_response, option.id, { 'data-event-id' => option.event_id }] }), {prompt: "Please select", class: 'form-control'}  %>
		</div>
		<div class="form-group">
			<label>With:</label>
			<%= select_tag :option_id4, options_for_select(Option.all.where(question_type: "With:").map{ |option| [option.possible_response, option.id, { 'data-event-id' => option.event_id }] }), {prompt: "Please select", class: 'form-control'} %>
		</div>
		<div class="form-group">
			<label>Date:</label>
			<input type="text" class="form-control" id="sandbox-container" name="answer[date]">
		</div>
		<div class="form-group">
			<label>Anything else?</label>
			<%= text_field :answer, :type_in, placeholder: "Type in...", class: "form-control" %>
		</div>
		<br>
	    <%= f.submit "Submit", class: "btn btn-default btn-block paperdolled-button" %>
	  </fieldset>
    <% end %>

app/views/users/index.html.erb

<% provide(:title, "Users") %>



<!-- content -->

	<div class="container-fluid">
	<div class="jumbotron" id='main-jumbotron'>
		<%= render "layouts/main_navbar" %>
	</div>
	</div>

	<div class="container">
			        <!-- These are our grid blocks --> 
		<% @users.in_groups_of(3,false).each do |group| %>
			<div class="row">

			<% group.each do |user| %>
				<div class="col-md-4">
				
					<h5><%= user.first_name + " " + user.last_name %></h5>
					<hr style="border-color: #cabe97 !important; border-top: 2px solid; margin-top: 10px;">
					<div class="center-block">
						<%= link_to user.picture? ? image_tag(user.picture, style: "height: auto; width: 100%; max-width: 360px; max-height: 360px;") : image_tag("http://placehold.it/300x300", style: "height: auto; width: 100%; max-width: 360px; max-height: 360px;"), user_path(user), class: "img-responsive" %>
					</div>		
					<br>
					<% scenario = User.list_answers(user) %>

					<p><span class="josefin-bold">Event: </span><%= scenario["Event"] %></p>
					<p><span class="josefin-bold">Event Location: </span><%= user.event_location? ? user.event_location : '-----' %></p>
					<p><span class="josefin-bold">Date: </span><%= scenario["Date"] %></p>
										
					<br>
					<%= link_to "Doll me up", new_user_outfit_path(user), class: "btn btn-default paperdolled-button", style: "width:40%;" %>
														
				</div>
			<% end %>
			
			</div>
		<% end %>

		<br>

		<%= will_paginate @users, class: 'center-block text-center' %>
				

		
	</div>

					

app/views/users/show.html.erb
<% provide(:title, "Profile") %>

<div class="container-fluid">
	<div class="jumbotron" id='main-jumbotron'>
		<%= render "layouts/main_navbar" %>
	</div>

	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="well">
				<div class="row" style="padding: 0px;">
					<div class="col-md-12">
						<h5 style="display: inline-block; margin-top:10px;">My Profile</h5>
						<%= link_to destroy_user_session_path, method: :delete do %>
						<button type="button" class="btn btn-primary paperdolled-warning-button-outline pull-right">
						  Log Out
						</button>
						<% end %>
						<hr style="border-color: #cabe97 !important; border-top: 2px solid; margin-top: 10px;">
						
					</div>
				</div>
				<div class="row">
					<div class="col-md-6">
			  			<%= @user.picture? ? image_tag(@user.picture, style: "height: auto; width: 100%; max-width: 550px; max-height: 550px;") : image_tag("http://placehold.it/300x300", style: "height: auto; width: 100%; max-width: 550px; max-height: 550px; margin: 0px;")%>

			  			<br><br>

			  			<button type="button" class="btn btn-primary paperdolled-button-outline center-block" id="upload-button">
						  Upload
						</button>	

			  			<div id="profile-pic" class="center-block" style="display: none;">
			  			<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => {:method => :put, :multipart => true}) do |f| %>

							<%= devise_error_messages! %><!--Check to make sure this works-->
				
			  				<div class="form-group">
								<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
								<%= f.hidden_field :picture_cache %>
							</div>

							<div class="form-group">
			    				<%= f.submit "Update", class: "btn btn-primary paperdolled-button" %>
			    				<button type="button" class="btn btn-danger" id="close-button">Close</button>
							</div>
		  				<% end %>
		  				</div>
					</div>
					<div class="col-md-6">
						<h4 class="josefin-bold"><%= @user.first_name + " " + @user.last_name %></h4>
						<hr style="border-color: #cabe97 !important; border-top: 2px solid; margin-top: 10px;">
						<div class="row">
						<div class="col-md-6">
							<p><span class="josefin-bold">Age: </span><%= link_to(@user.age.nil? ? "Write something here!" : "#{@user.age}", "#", remote: true, :"data-url" => user_update_path(id: @user.id), id: :bio, :'data-name' => :age, :"data-type" => "text", :"data-disabled" => @disabled, style: "border-bottom: none; color: black; font-size: 14px;") %></p>
							<p><span class="josefin-bold">Style Likes: </span><%= link_to(@user.style_likes.nil? ? "Write something here!" : "#{@user.style_likes}", "#", remote: true, :"data-url" => user_update_path, id: :bio, :'data-name' => :style_likes, :"data-type" => "text", :"data-disabled" => @disabled, style: "border-bottom: none; color: black; font-size: 14px;") %></p>
							<p><span class="josefin-bold">Style Dislikes: </span><%= link_to(@user.style_dislikes.nil? ? "Write something here!" : "#{@user.style_dislikes}", "#", remote: true, :"data-url" => user_update_path, id: :bio, :'data-name' => :style_dislikes, :"data-type" => "text", :"data-disabled" => @disabled, style: "border-bottom: none; color: black; font-size: 14px;") %></p>
							<p><span class="josefin-bold">Style Icon: </span><%= link_to(@user.style_icon.nil? ? "Write something here!" : "#{@user.style_icon}", "#", remote: true, :"data-url" => user_update_path, id: :bio, :'data-name' => :style_icon, :"data-type" => "text", :"data-disabled" => @disabled, style: "border-bottom: none; color: black; font-size: 14px;") %></p>
							<br>
							<p><span class="josefin-bold">Event Location: </span><%= link_to(@user.event_location.nil? ? "-----" : "#{@user.event_location}", "#", remote: true, :"data-url" => user_update_path, id: :bio, :'data-name' => :event_location, :"data-type" => "text", :"data-disabled" => @disabled, style: "border-bottom: none; color: black; font-size: 14px;") %></p>
						</div>
						<div class="col-md-6">
							<p><span class="josefin-bold">Event: </span><%= @scenario["Event"] %></p>
							<p><span class="josefin-bold">And: </span><%= @scenario["And"] %></p>
							<p><span class="josefin-bold">Also: </span><%= @scenario["Also"] %></p>
							<p><span class="josefin-bold">With: </span><%= @scenario["With"] %></p>
							<p><span class="josefin-bold">Date: </span><%= @scenario["Date"] %></p>
							<p><span class="josefin-bold">Other: </span><%= @scenario["Other"] %></p>
						</div>
						</div>
						<div class="row">
						<div class="col-md-6">
							<%= link_to "Doll me up", new_user_outfit_path(@user), class: "btn btn-default paperdolled-button", style: "width:55%;" %>
						</div>
						<div class="col-md-6">
							<% if can? :update, @user %>
								<button type="button" class="btn btn-primary paperdolled-button text-center" style="width:55%;" data-toggle="modal" data-target="#myModal">
								  Plan for an event!
								</button>
							<% end %>
						</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-6 col-md-offset-6">
						
					</div>
				</div>
		
			
				<script type="text/javascript">
				  $('#picture').bind('change', function() {
				    var size_in_megabytes = this.files[0].size/1024/1024;
				    if (size_in_megabytes > 5) {
				      alert('Maximum file size is 5MB. Please choose a smaller file.');
				    }
				  });
				</script>
			
				<!--
				<div class="row">
					<div class="col-md-6 col-centered">
				
						<%= link_to(@user.bio.nil? ? "Please fill out your bio" : "#{@user.bio}", "#", remote: true, :"data-url" => user_update_path, id: :bio, :'data-name' => :bio, :"data-type" => "textarea", style: "border-bottom: none; color: black; font-size: 20px;") %>
					
				
					</div>
				</div>
				-->

			</div>
		</div>
	</div>
			
	<% @outfits.in_groups_of(3, false).each do |group| %>		
	<div class="row" style="background-color:<%= cycle('black', 'white') -%>; padding-bottom: 30px;" id="outfit">
	<div class="col-md-8 col-md-offset-2">
		<% group.each do |outfit| %>
			<div class="col-md-4">
			<%= link_to user_outfit_path(@user, outfit) do %>
				<div class="small_outfit_canvas" style="background-color: white;">
					<% outfit.items.map do |item| %>
						<div class="small_draggable2" data-item-id='<%= item.id %>' data-top='<%= item.closets.find_by(outfit_id: outfit.id).y_coordinate %>' data-left='<%= item.closets.find_by(outfit_id: outfit.id).x_coordinate %>' data-height='<%= item.closets.find_by(outfit_id: outfit.id).height %>' data-width='<%= item.closets.find_by(outfit_id: outfit.id).width %>'>
							<%= image_tag item.picture, class: "imageUpload" %>	
						</div>
					<% end %>
				</div>
			<% end %>
				<p style="color:<%= cycle('white', 'white', 'white', 'black', 'black', 'black') -%>;">
					Stylist: <%= link_to "#{outfit.stylist.first_name} #{outfit.stylist.last_name}", user_path(outfit.stylist_id) %>
				</p>
			</div>
		<% end %>
	</div>
	</div>
	<% end %>		  
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Select all relevant options.</h4>
      </div>
      <div class="modal-body">
        <%= render 'answers' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>
