config/routes.rb
Rails.application.routes.draw do
  
  devise_scope :user do
    get "/" => "registrations#new"
    get 'users/sign_in', to: redirect('/')
    get 'users/sign_up', to: redirect('/')
    put '/update' => "registrations#update", as: "user_update"
    get 'users/edit' => "registrations#edit", as: "devise_user_edit"
    get 'users/:id' => "users#show", as: "user_show"
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }

  resources :users do 
    resources :outfits
    resources :closets, only: [:create]
  end

  resources :scenarios
  resources :answers
  resources :items
  
  get '/about' => 'welcome#about', as: "about"
  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
      can :read, :all
      can [:update, :destroy], User, :id => user.id
      can [:destroy], Outfit, :styled_id => user.id
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :scenario
  belongs_to :option
  
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
  
  
end

app/models/closet.rb
class Closet < ActiveRecord::Base
  belongs_to :outfit
  belongs_to :item
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :options
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :closets, dependent: :destroy
  has_many :outfits, :through => :closets
end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :event
  has_many :answers
end

app/models/outfit.rb
class Outfit < ActiveRecord::Base
  belongs_to :styled, :class_name => "User", :foreign_key => "styled_id"
  belongs_to :stylist, :class_name => "User", :foreign_key => "stylist_id"
  has_many :closets, dependent: :delete_all
  has_many :items, :through => :closets
end

app/models/scenario.rb
class Scenario < ActiveRecord::Base
  belongs_to :user
  has_many :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
         
  mount_uploader :picture, PictureUploader
  
  has_many :scenarios
  has_many :outfits
  has_many :authentications
  

                
  validates :first_name,  presence: true
  validates :last_name,  presence: true
  validate  :picture_size
  
         
  def apply_omniauth(auth)
    self.email = auth.email
    self.remote_picture_url = auth.info.image if self.picture.blank?
    self.first_name = auth.info.first_name
    self.last_name = auth.info.last_name
    authentications.build(provider: auth.provider, uid: auth.uid, token: auth.extension.token)
  end       

  def self.from_omniauth(auth)
    if self.where(email: auth.info.email).exists?
      existing_user = self.where(email: auth.info.email).first
      existing_user.provider = auth.provider
      existing_user.uid = auth.uid
      existin_user.remote_picture_url = auth.info.image if existing_user.picture.blank?
    else
      existing_user = where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.first_name = auth.info.first_name   # assuming the user model has a name
        user.last_name = auth.info.last_name
        user.remote_picture_url = auth.info.image # assuming the user model has an image
      end
    end
    existing_user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  
  # Returns search query
  def self.search(params)
    where("(UPPER(first_name) LIKE ?) OR (UPPER(last_name) LIKE ?)", "%#{params.upcase}%", "%#{params.upcase}%") 
  end

  # Find user responses for scenarios
  def self.list_answers(user)
    # responses = []
    sub_responses = {}
	  scenario = user.scenarios.order("created_at").last
    if !scenario.nil?
      sub_responses["Event"] = scenario.answers.first.option.event.dress_me_for
		  scenario.answers.map do |answer|
        #sub_responses << options.possible_response if !options.nil?
        #response = options.possible_response if !options.nil?
        if !answer.option_id.nil?
          options = Option.all.find_by(id: answer.option_id)
          case options.question_type
          when "And:"
            sub_responses["And"] = options.possible_response if !options.nil?
          when "Also:"
            sub_responses["Also"]= options.possible_response if !options.nil?
          when "With:"
            sub_responses["With"] = options.possible_response if !options.nil?
          end
        end
        if answer.type_in.present?
            sub_responses["Other"] = answer.type_in
        end
        if answer.date.present?
            sub_responses["Date"] = answer.date
        end
      end
    end
      #responses << sub_responses
		
    #responses
    sub_responses.default = "-----"
    #responses = []
    #responses << sub_responses
    return sub_responses
  end 


  
  private
  
  # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:index]
  
  def index
    @items = Item.all.paginate(:page => params[:page])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :json, :html
  
  def index
    if params[:query]
      @users = User.search(params[:query])
    else
      @users = User.all.paginate(:page => params[:page], :per_page => 30)
    end
  end

  def show
    @user = User.find(params[:id])
    @scenario = User.list_answers(@user)
    @answer = Answer.new
    @options = Option.all
    @outfits = Outfit.where(styled_id: @user.id)
    @disabled = @user == current_user ? false : true
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end
  
  def resource
    @resource ||= User.new
  end
  
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  

end

app/helpers/closets_helper.rb
module ClosetsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/outfits_helper.rb
module OutfitsHelper
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_main_navbar.html.erb
  	<h2 class='text-center josefin-bold', style="color: #978b64; font-size: 40px;">Paperdolled</h2>
  	<br>
	<div class="btn-group btn-group-justified main-nav-group" role="group" aria-label="...">
	  <div class="btn-group" role="group">
	  	<% if current_user.present? %>
	  		<%= link_to(users_path) do %>
	    		<button type="button" class="btn btn-default main-nav-buttons">
	    			HOME
	    		</button>
	    	<% end %>
	    <% else %>
	    	<%= link_to(root_path) do %>
	    		<button type="button" class="btn btn-default main-nav-buttons">
	    			SIGN IN
	    		</button>
	    	<% end %>
	    <% end %>
	  </div>
	  <div class="btn-group" role="group">
	  	<%= link_to(about_path) do %>
	    	<button type="button" class="btn btn-default main-nav-buttons">
	    		ABOUT
	    	</button>
	    <% end %>
	  </div>
	  <% if current_user %>
	  	<div class="btn-group" role="group">
	  		<%= link_to(user_path(current_user.id)) do %>
	  	  	<button type="button" class="btn btn-default main-nav-buttons">
	  	  		PROFILE
	  	  	</button>
	  	  <% end %>
	  	</div>
	  <% end %>
	  <div class="btn-group" role="group">
	  	<%= link_to(items_path) do %>
	    	<button type="button" class="btn btn-default main-nav-buttons">
				GALLERY
	    	</button>
	    <% end %>
	  </div>
	</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  	<title><%= yield(:title) %> | Paperdolled</title>
  	<%= stylesheet_link_tag    'application', media: 'all' %>
  	<%= javascript_include_tag 'application' %>
  	<%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	</head>
	<body class="<%= controller_name %> <%= action_name %>">

		<%= render 'layouts/messages' %>
	    <%= yield %>
		<%= debug(params) if Rails.env.development? %>

	</body>
</html>